# Site settings
title: maraoz.com
description: > # this means to ignore newlines until "baseurl:"
  Manuel Araoz's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maraoz.com" # the base hostname & protocol for your site
twitter_username: maraoz
github_username: maraoz
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
