title: maraoz.com
description: >
  Manuel Araoz's personal website.
baseurl: ""
url: "https://maraoz.com"
twitter_username: maraoz
github_username: maraoz
permalink: pretty

collections:
  journal:
    output: true
    permalink: journal/:timestamp

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
